"""add allow_negative to accounts

Revision ID: 4866aaad41a6
Revises: c73b77613de8
Create Date: 2026-10-09 09:44:38.081736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4866aaad41a6'
down_revision: Union[str, Sequence[str], None] = 'c73b77613de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('allow_negative', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'allow_negative')
    # ### end Alembic commands ###
